package com.example.upcycle.navigation

const val ROUTE_REGISTER="register"
const val ROUTE_LOGIN="login"
const val ROUTE_ADMIN_HOME="Admin home"
const val ROUTE_SPLASH="SplashScreen"
const val ROUTE_ADD_PRODUCT="evaluation"
const val ROUTE_UPDATE_PRODUCT="Update Evaluation"
const val ROUTE_USER_HOME="User home page"
const val ROUTE_ADMIN_LOGIN="Admin login"
const val ROUTE_POST_PRODUCT="Admin product"
const val ROUTE_PRODUCT_DETAILS="Product Details"
const val ROUTE_USER_PROFILE="User profile"
const val ROUTE_USER_PRODUCTS="User Products Uploaded"
const val ROUTE_ADMIN_PROFILE="Admin profile"